.\" Process this file with
.\" groff -man -Tascii vimprobable2.1
.\"
.TH VIMPROBABLE2 1 "JANUARY 2010" "Linux User Manuals"
.SH NAME
Vimprobable \- A WWW browser based on webkit with keybindings inspired by vim, the great editor.

.SH SYNOPSIS
.B vimprobable2
.OP \fL\-b|\-\-bookmarktag
.OP \fL\-c|\-\-config
.OP \fL\-e|\-\-embed
.OP \fL\-h|\-\-help
.OP \fL\-v|\-\-version
.OP URI

.SH OPTIONS
.TP
.BI -b " bookmark tag"
Open URLs specified with the given tag.
.TP
.BI -c " config file"
Use the specified config file.  If none found, defaults to
.I $HOME/.config/vimprobable/vimprobablerc
.TP
.BI -e " windowid"
Given the windowid of an XEmbed-aware application, Vimprobable will use that as its parent.
.TP
.BI -h
Prints out a short usage summary.
.TP
.BI -v
Prints the version of Vimprobable.

.SH DESCRIPTION
Vimprobable is a WWW browser that is build around the webkit library. Vimprobable is fast. 
Vimprobable comes without buttons and other graphic widgets. It is aimed at being controlled 
as mouseless as possible. It uses keybindings that are inspired by vim, the great editor.
.PP
Just like vim, moving through the webpage can be done by entering commands by the keyboard.
Most of these commands require just one or two keystrokes.
.PP
Vimprobable mimics the ex-commandmode of vim. By entering a colon (:) commands like open,
set and map can be entered.

.SH QUICK START

Don't want to read this entire manpage? Here are a few basic steps:

.I "    " o
Insert URL from keyboard and load it

.I "    " t
Insert URL from keyboard and load it into new window

.I "    " j
Scroll down

.I "    " k
Scroll up

.I "    " d  
Close current window

.SH KEYBOARD BINDINGS
The default keyboard bindings are explained in this sections. These keybindings
can be changed.

.IP "Move through current page"
Vimprobable recognizes the following motion commands:
0, $, g, <shift>G, h, j, k, l, Ctrl-b, Ctrl-f, Ctrl-d, Ctrl-u, Ctrl-e, Ctrl-y

.IP "Move through pages"
Ctrl-i, Ctrl-o, <shift>H, <shift>L
.PP
These commands are used to walk through the browse-history.

.IP "Reloading and cancel loading"

.I "    " r 
Reload

.I "    " <shift>R
Force reload

.I "    " c
Cancel load

.IP "Zoom in and out"

.I "    " zi
Zoom text in

.I "    " zI
Zoom full content in

.I "    " zo
Zoom text out

.I "    " zo
Zoom full content out

.I "    " zz
Zoom reset

.I "    " zZ
Zoom reset

.IP "URL commands"

.I "    " y
Yank current URL into clipboard

.I "    " Y
Yank current selection into clipboard

.I "    " gu
Load URL one directory up

.I "    " gu
Load rootdirectory of current URL

.I "    " gh
Load homepage

.I "    " gH
Load homepage into new window

.I "    " p
Load URL from clipboard

.I "    " P
Load URL from clipboard into new window

.I "    " o
Insert URL from keyboard and load it

.I "    " t
Insert URL from keyboard and load it into new window

.I "    " u
Open a new window with the URL which has been closed last


.IP Search

.I "    " /
Start search

.I "    " ?
Start backward search

.I "    " n
Next search result



.SH COLON COMMANDS

The following commands are entered after first entering a colon (:)

.IP ":open "

Insert URL from keyboard and load it

Shortcut: o

.IP ":tabopen "

Insert URL from keyboard and load it into new window

Shortcut: t

.IP ":bma or :bookmark"

Bookmarks the current page. 

Bookmarks are retrieved by tabcompletion when entering a new URL.

You can add tags to the bookmarks by just adding words after the command, e.g.

:bma tag1 tag2 tag3

.IP ":qt "

Open all bookmarks containing a certain tag in new windows.

.IP ":fo[rward] and :ba[ck]"

The commands :fo, :forward, :ba and :backward moves through the browse-history

.IP ":re[load], :re! and :reload!"

The commands :re, :reload, ;re! and :reload! are given to reload or
force reload.

.IP ":st[op]"

Cancel current loading

.IP ":source"

Toggles between normal view and sourcecode view.


.IP ":set"

Change default settings on the fly. See man vimprobablerc for the list of
settings to be changed.

.IP ":map"

Change default keybindings on the fly. See man vimprobablerc for the list of
mappings to be changed.

.IP ":quit"

Close current window

Shortcut: d

.IP ":print"

Print the current URL

.SH QUICKMARKS

Up to 9 quickmarks can be defined. These are stored as quickmark 1 up to
quickmark 9.  You can store the URI of the current
page as quickmark with

.I :set qmark=<hotkey>

Later you can recall the quickmark with

.I q<hotkey>

Example:

:set qmark=4
Store current URI as quickmark 4

q4
Recall quickmark 4

.SH FILES

Please make sure you create these files before running the browser. 
Everything but the history, bookmarks and closed files is optional. The cookies
file is required if you want to use cookies.

.I $HOME/.config/vimprobable/vimprobablerc

.I $HOME/.config/vimprobable/bookmarks

.I $HOME/.config/vimprobable/cookies

.I $HOME/.config/vimprobable/history

.I $HOME/.config/vimprobable/closed

.I $HOME/.config/vimprobable/quickmarks

.I $HOME/.config/vimprobable/style.css


.SH BUGS
There has not been any significant bug-hunting yet.
.SH AUTHORS
Hannes Schueller and Matto Fransen
.SH "SEE ALSO"
.BR vimprobablerc (1),



